language: python
python:
    - "2.7"
install:
    - pip install .
    - pip install -r requirements.txt
    - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
    - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
script: python setup.py nosetests

